# Generated by Django 4.2.5 on 2023-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="post/cover_image/%Y%m%d/",
                verbose_name="封面圖片",
            ),
        ),
    ]
